<div class="page-wrapper" >
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="<?php echo TEMPLATE_URI; ?>/js/scripts.js" ></script>
<a name="top"></a>
<header class='header' >

    <div class='inner'>

            <div id='logo' >
                <a href="<?php echo BASE_URL; ?>" >
                <img src='<?php echo TEMPLATE_URI; ?>/img/Savino-Miller-Logo.svg' />
                </a>
            </div>



        <div class="mobile-menu">
            <div class="menu-toggle">
                <a id="toggleMenuIcon" href="javascript:toggleMenu()" >
                        <div style="  width: 30px;height: 1px;background-color: #48B9C7;margin: 6px 0;"></div>
                        <div style="  width: 30px;height: 1px;background-color: #48B9C7;margin: 6px 0;"></div>
                        <div style="  width: 30px;height: 1px;background-color: #48B9C7;margin: 6px 0;"></div>
                </a>
            </div>
        </div>

        <div id="mobile-menu-wrapper" class="mobile-menu" >
            <div id="mobile-menu-menu-container" >

            </div>
        </div>

        
        <div id="socialMedia">
        <a href="https://www.instagram.com/savinomillerdesignstudio/" target="_blank" class="fa fa-instagram"></a>
        <a href="https://www.facebook.com/SavinoMiller/" target="_blank" class="fa fa-facebook-square"></a>
        <a href="https://www.linkedin.com/company/savino-miller-design-studio/" target="_blank" class="fa fa-linkedin-square"></a>
        <a href="https://www.youtube.com/channel/UC9WMosWiKfj4z5KQcpjIM0A" target="_blank" class="fa fa-youtube-play"></a>
        </div>
        


        <nav id="desktop-menu" class="main-menu" >
            <?php wp_nav_menu(array('theme_location' => 'main-menu')); ?>
            <div class="project-category-menu  menu" >
                <?php echo PartialRenderer::render(TEMPLATE_DIR.'/views/_partial/project-category-nav.phtml',array()); ?>
            </div>
            <div id="current-cat-name" >

            </div>
            <div id="about-menu" class="" >
                <?Php echo wp_nav_menu(array('theme_location' => 'about-sub-menu')); ?>
            </div>
            <div id="current-about-name" >
            </div>
        </nav>

        <div class="clearfix">&nbsp;</div>
        <nav id="layer-menu-target" class="inner desktop-only">

        </nav>
        <nav id="layer-menu-target-2" class="inner desktop-only">

        </nav>
    </div>

    <div class="clearfix">&nbsp;</div>
</header>


<script>


var menuState = 'in';
function toggleMenu(){
    if(menuState == 'in'){
        $('#toggleMenuIcon').html(`<div style="margin-top:12px"><div style="width: 30px;height: 1px;background-color: #48B9C7;margin: 6px 0;transform: rotate(45deg);"></div>
                                   <div style="width: 30px;height: 1px;background-color: #48B9C7;margin: -6px 0;transform: rotate(-45deg);"></div></div>`);

        $('.project-nav').fadeOut('slow',function(){
            $('#mobile-menu-menu-container').slideDown();
        });

        if($('.project-nav').length <= 0){
            $('#mobile-menu-menu-container').slideDown();
        }
        menuState = 'out';
    }else{
        
        $('#toggleMenuIcon').html(`<div style="  width: 30px;height: 1px;background-color: #48B9C7;margin: 6px 0;"></div>
                                   <div style="  width: 30px;height: 1px;background-color: #48B9C7;margin: 6px 0;"></div>
                                   <div style="  width: 30px;height: 1px;background-color: #48B9C7;margin: 6px 0;"></div>`);
        $('#mobile-menu-menu-container').slideUp('slow',function(){
            $('.project-nav').fadeIn();
        });

        if($('.project-nav').length <= 0){
            $('#mobile-menu-menu-container').slideUp();
        }
        menuState = 'in'
    }


}


$(document).ready(function(){
    var htmlMenu = $('#desktop-menu').html();
    $('#mobile-menu-menu-container').html(htmlMenu+`
        <div id="socialMedia2" style="margin-top:10px;">
        <i onclick='javascript:window.open("https://www.instagram.com/savinomillerdesignstudio/","_blank")' style="font-size:20px;color:#AAAAAA;text-decoration:none;width:30px;" class="fa fa-instagram"></i>
        <i onclick='javascript:window.open("https://www.facebook.com/SavinoMiller/","_blank")' class="fa fa-facebook-square"></i>
        <i onclick='javascript:window.open("https://www.linkedin.com/company/savino-miller-design-studio/","_blank")' class="fa fa-linkedin"></i>
        <i onclick='javascript:window.open("https://www.youtube.com/channel/UC9WMosWiKfj4z5KQcpjIM0A","_blank")' class="fa fa-youtube-play"></i>
        </div>
    `);

    var aboutMenu = $('#about-menu > div').html();
    $('#desktop-menu #about-menu').remove();
    var projectCategoryMenu = $('#desktop-menu .project-category-menu').html();
    $('#desktop-menu .project-category-menu').remove();
    $('#layer-menu-target').append('<div class="layer-menu project-category-menu" >'+projectCategoryMenu+'</div>');
    $('#layer-menu-target-2').append('<div class="layer-menu menu-about-sub-menu-container" >'+aboutMenu+'</div>');

    var layerMenuTargetHtml = $('#layer-menu-target').html();
    $('#layer-menu-target').remove();

    var layerMenuTargetHtml2 = $('#layer-menu-target-2').html();
    $('#layer-menu-target-2').remove();


    $('.menu-item-10 a').attr('href','javascript:toggleCategories()');
    $('.menu-item-22 a').attr('href','javascript:toggleAbout()');

    $('.menu-item-10 a').after('<div id="layer-menu-target" class="desktop-only" >'+layerMenuTargetHtml+'</div>');
    $('.menu-item-22 a').after('<div id="layer-menu-target-2" class="desktop-only" >'+layerMenuTargetHtml2+'</div>');

    $('#layer-menu-target .menu-about-sub-menu-container ul').addClass('sub-nav');
    $('#layer-menu-target-2 .menu-about-sub-menu-container ul').addClass('sub-nav');
});



//$('.menu-main-menu-container').after($('#about-menu').html());
//$('#about-menu').remove();
//$('.main-menu #menu-about-sub-menu').addClass('sub-nav');

function toggleCategories(){
    $('.project-category-menu').toggle();
    $('.menu-about-sub-menu-container').hide();
}

function toggleAbout(){

    $('.project-category-menu').hide();
    $('.menu-about-sub-menu-container').toggle();
}

toggleAbout();


</script>

<!--Place the hr underline under the active site-->
<?php
echo "<script>console.log('".$_SERVER['REQUEST_URI']."');</script>";
if ((strpos($_SERVER['REQUEST_URI'],'portfolio') !== false) || (strpos($_SERVER['REQUEST_URI'],'projects') !== false)) {
?>
<style>
#hr {  
  margin-left: 6.5%;
  width: 24%;
  background: rgb(128,128,128,0.5);
}
</style>
<?php
}
else if (strpos($_SERVER['REQUEST_URI'],'news') !== false) {
?>
<style>
#hr {  
  margin-left: 60%;
  width: 12.5%;  
  background: rgb(128,128,128,0.5);
}
</style>
<?php 
}
else if (strpos($_SERVER['REQUEST_URI'],'contact') !== false) {
?>
<style>
#hr {    
  margin-left: 80.25%;
  width: 19.5%;
  background: rgb(128,128,128,0.5);
}
</style>
<?php 
}
else if ($_SERVER['REQUEST_URI'] !== '/') {
?>
<style>
#hr {  
  margin-left: 37.5%;
  width: 15.5%;
  background: rgb(128,128,128,0.5);
}
</style>
<?php 
}
?>
<script>
setTimeout(function() {
$('.menu').not(".sub-nav").append('<div id="hr"></div>');
}, 600);
</script>
<style>
@media only screen
and (max-width : 600px) {
    #hr {
        display: none;
    }
}
</style>