<?php
/** @var $entity SMAwardEntity */
$entity = $partialObj;
if (strpos($_SERVER['REQUEST_URI'], 'awards')) {
?>
<div class='award-teaser' >
    <?php echo "<img class='award-teaser-image' ".explode("<img",$entity->content)[1]; ?>
    <div class="award-teaser-title"><?php echo $entity->title; ?></div>
</div>
<?php } else { 
    ?>
    <style>
        .news-date {
            font-size: 24px;
            color: #7B8080;
            font-family: "Segoe UI Light";
            text-align: left;
        }
        .news-title {
            font-size: 24px;
            color: #7B8080;
            font-family: "Segoe UI Semi-Bold";
            text-align: left;
        }
        .news-description {
            font-size: 20px;
            color: #7B8080;
            font-family: "Segoe UI Light";
            text-align: left;
        }
    </style>
<div class='award-teaser' >
    <?php preg_match('/<img.+src=[\'"](?P<src>.+?)[\'"].*>/i', $entity->content, $image); echo isset($image[1]) ? "<img class='award-teaser-image' src='".$image[1]."'>" : ""; ?>
    <div class="news-date"><?php $dateArray = explode(".",$entity->title); echo $dateArray[0].'.'.$dateArray[1].'.'.substr($dateArray[2],0,2); ?></div>
    <div class="news-title"><?php echo substr($dateArray[2], 2); ?></div>
    <div class="news-description"><?php echo preg_replace("/<img[^>]+\>/i", "", preg_replace("/<video[^>]+\>/i", "", $entity->content)); ?></div>
</div>
<?php } ?>