<?php
function wp_list_categories_for_post_type($post_type, $args = '') {
    $exclude = array();

    // Check ALL categories for posts of given post type
    foreach (get_categories() as $category) {
        $posts = get_posts(array('post_type' => $post_type, 'category' => $category->cat_ID));
        // If no posts found, ...
        if (empty($posts)){
            // ...add category to exclude list
            $exclude[] = $category->cat_ID;
        }
    }

    // Set up args
    if (! empty($exclude)) {
        $args .= ('' === $args) ? '' : '&';
        $args .= 'exclude='.implode(',', $exclude);
    }

    $args .= '&orderby=description&order=ASC';

    // List categories
    return wp_list_categories($args);
}


?>


<ul class="cat-nav sub-nav" >
    <?php
    echo str_replace('category/','portfolio/?cat=',wp_list_categories_for_post_type('smprojectentity','echo=0&title_li=0&use_desc_for_title=0'));
    ?>
</ul>
