<?php
$entity = $partialObj;
?>
<style>
@media only screen
and (max-width : 1024px){
    .portraitImage{
        width: 48% !important;
        height: 50% !important;
    }
}
</style>
<div id="single-project-wrapper" style="margin-top:120px;" >
        <?php
        $homeUrl = home_url().'/';

        echo "<div class='single-project-title' style='line-height:30px;'>".$entity->title."</div>";
        if ($entity->projectDate!=="") {
            echo "<div class='single-project-subtitle'>".$entity->projectDate."</div>";
        }
        echo '<script>console.log('.json_encode($entity).');</script>';

        $portraitImages=[];
        $landscapeImages=[];
        foreach($entity->imageGallery1 as $index=>$image){
            $image->resize(1600,2600,0);
            $contentPath = str_replace($homeUrl,'',$image->urlsized);
            $size = getimagesize($contentPath);
            $imageWidth=getimagesize($image->urlsized)[0];
            $imageHeight=getimagesize($image->urlsized)[1];
            if ($imageWidth>$imageHeight) {
                $margins="margin-top:15px;margin-bottom:0px;";
                if ($index==0) {
                    $margins="margin-top:15px;margin-bottom:40px;";
                }
                else if ($index==count($entity->imageGallery1)) {
                    $margins="margin-top:40px;margin-bottom:0px;";
                }
                $landscapeImages[] = '<img src="'.$image->urlsized.'" style="object-fit:cover;width:100%;'.$margins.'">';
            }
            else {
                $portraitImages[] = '<img class="portraitImage" src="'.$image->urlsized.'" style="object-fit:cover;width:49.5%;height:1000px;margin-top:15px;margin-bottom:0px;';
            }
            //echo '<script>console.log('.json_encode($image).');</script>';
            //echo '<script>console.log('.json_encode(getimagesize($image->urlsized)).');</script>';
        }

        if (count($landscapeImages)==0) {
            foreach($portraitImages as $index=>$image) {
                if ($index==0 || $index==2 || $index==4) {
                    if ($index==0) {echo "<div style='height:940px'>";}
                    echo $image.'float:left;">';
                }
                else if ($index==1 || $index==3 || $index==5) {
                    echo $image.'float:right;">';
                }

                if ($index==1) {
                    echo "</div><div class='single-project-description' style='margin-top:105px;'>".MyHelpers::pToEmptyLine($entity->content)."</div>";
                }
            }
        }

        $nextPortraitStack=0;
        foreach($landscapeImages as $index=>$image) {
            if ($index==0 || $index==1) {
                echo $image;
                if ($index==0) {echo "<div class='single-project-description'>".MyHelpers::pToEmptyLine($entity->content)."</div>";}
                if (!array_key_exists($index+1,$landscapeImages)) {
                    foreach($portraitImages as $innerIndex=>$innerImage) {
                        if ($innerIndex==0 || $innerIndex==2 || $innerIndex==4) {
                            echo $innerImage.'float:left;">';
                        }
                        else if ($innerIndex==1 || $innerIndex==3 || $innerIndex==5) {
                            echo $innerImage.'float:right;">';
                        }
                    }
                }
            }
            else if ($index==2 && count($portraitImages)>0) {
                foreach($portraitImages as $innerIndex=>$innerImage) {
                    if ($innerIndex==0) {
                        echo $innerImage.'float:left;">';
                    }
                    else if ($innerIndex==1) {
                        echo $innerImage.'float:right;">';
                    }
                    else {
                        if ($nextPortraitStack!=1) {
                            echo $image;
                            $nextPortraitStack=1;
                        }
                    }
                }
            }
            else {
                echo $image;
            }

            if ($nextPortraitStack==1) {                
                foreach($portraitImages as $innerIndex=>$innerImage) {
                    if ($innerIndex==2||$innerIndex==3) {
                        echo $innerImage;
                    }
                    else {
                        $nextPortraitStack=2;
                    }
                }
            }
        }
        ?> 
</div>