<?php
/** @var $entity SMPersonEntity */
$entity = $partialObj;
//print_r($entity);
$resumeUrl = '';
if('' != $entity->resume){
    $resumeObj = new MediaEntity($entity->resume);
    $resumeUrl = $resumeObj->url;
}
if (!strpos($_SERVER['REQUEST_URI'], 'staff')) {
    echo '<script>console.log('.json_encode($entity).')</script>';
    $metaArray = explode("#", $entity->rawContent);
    $profileArray = [];
    foreach ($metaArray as $index=>$object) {
        $profileArray[substr(explode(chr(10),trim($object))[0],0,-1)] = nl2br(substr(strstr($object,chr(10)), 1));
    }
    echo '<script>console.log('.json_encode($profileArray).')</script>';
?>
    <style>
    #FeaturedImage {
        margin-left: 0px;
        margin-right:3vw;
        float:left;
        margin-bottom: 65vh;
    }
    #Title {
        color: #666666;
        font-size:24px;
        margin:20px;
        margin-bottom:0px;
        font-family: "Segoe UI Semi-Bold";
        margin-top:-5px;
    }
    #Subtitle {
        color: #666666;
        font-size:24px;
        margin:20px;
        margin-top:0px;
        font-family: "Segoe UI Light";
    }
    #Description {
        color: #666666;
        font-size:18px;
        font-family: "Segoe UI Light";
    }
    @media only screen and (max-width: 800px) {
        #FeaturedImage {
            margin-bottom:20px;
        }
        img {
            width:100vw;
        }
        #main-content .inner {
        margin-left: 0px !important;
        }
        #Title {
            width: 90vw;
        }
        #Subtitle {
            width: 90vw;
        }
        #Description {
            margin:20px;
            width: 90vw;
        }
    }
    </style>
    <div id='FeaturedImage'>
        <?php
        if(isset($entity->featuredImage)){
            $entity->featuredImage->resize(300,300,1);
            echo $entity->featuredImage->imgtagsized;
        }
        ?>
    </div>
    <div id='Title'><?php echo explode(chr(10),$profileArray['Name'])[0]; ?></div>
    <div id='Subtitle'><?php echo explode(chr(10),$profileArray['Name'])[1]; ?></div>
    <div id='Description'><?php echo $profileArray['Description']; ?></div>

<?php
}
else {
?>

<div class='project-teaser person-teaser' >
    <?php
    echo '<script>console.log('.json_encode($entity).')</script>';
    if('' != $entity->url){
        echo '<a href="'.$entity->url.'" target="_self" >';
        //echo '<a href="'.$entity->url.'" target="_self" >';
    }
    ?>
    <div class='thumb' >
        <?php
        if(isset($entity->featuredImage)){
            $entity->featuredImage->resize(500,500,1);
            echo $entity->featuredImage->imgtagsized;
        }else{
            echo '<img src="'.TEMPLATE_URI.'/img/placeholder-square.png" />';
        }
        ?>
    </div>
    <?php
    if('' != $resumeUrl){
        echo '</a>';
    }
    ?>
    <div class='person-info' >
        <br>
        <h2 style="font-family: 'Segoe UI';"><?php echo $entity->title; ?></h2>
        <span class="subline" ><?php echo $entity->corporateTitle; ?></span>
        <!--<div class='person-cv' >
            <php echo $entity->cv; ?>
        </div>-->
        <!--php
        if('' != $entity->email){
        ?>
        <a class="award-link person-link" href="mailto:<php echo $entity->email; ?>" ><php echo $entity->email; ?></a>
        <Php
        }
        ?-->
    </div>
</div>

<?php } ?>